version: "3"
services:
    go_server:
        build: go/server
        ports:
            - 3001:3001

    nodejs_simple_cluster:
        build:
            context: nodejs
            args:
                - variant=simple_cluster
        ports:
            - 3001:3001

    nodejs_many_accepts:
        build:
            context: nodejs
            args:
                - variant=many_accepts
        ports:
            - 3001:3001

    c_single:
        build:
            context: c
            args:
                - variant=single
        ports:
            - 3001:3001

    c_proc_spawn:
        build:
            context: c
            args:
                - variant=proc_spawn
        environment:
            - WORKER_COUNT=1000
        ports:
            - 3001:3001

    apache_httpd_event:
        build:
            context: apache_httpd
            args:
                - variant=event
        ports:
            - 3001:80

    apache_httpd_worker:
        build:
            context: apache_httpd
            args:
                - variant=worker
        ports:
            - 3001:80

    apache_httpd_prefork:
        build:
            context: apache_httpd
            args:
                - variant=prefork
        ports:
            - 3001:80
